register:
    resource:
        path: ../src/User/Infrastructure/Symfony/Controller/
        namespace: App\User\Infrastructure\Symfony\Controller
    type: attribute


api_login:
    path: /api/login_check
